# Generated by Django 4.2.7 on 2023-11-19 05:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('itemCode', models.CharField(max_length=255)),
                ('itemName', models.CharField(max_length=255)),
                ('itemPrice', models.IntegerField()),
                ('itemCat', models.ManyToManyField(blank=True, related_name='products', to='product.category')),
            ],
        ),
    ]
