# Generated by Django 4.2.7 on 2023-11-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='itemPrice',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
